#!/usr/bin/env escript
%% -*- erlang -*-

main([TargetDir | Version]) ->
  %% Construct list of apps sinan is dependent on
  Deps = [kernel, stdlib, compiler],

  %% Construct release tuple
  R = {release, {"OTP  APN 181 01", lists:flatten(Version)}, {erts, erlang:system_info(version)},
       [vsn_tuple(D) || D <- Deps]},

  %% Make the release_package directory and drop the .rel file into it
  PkgDir = filename:join([TargetDir, "erl-" ++ erlang:system_info(version)]),
  Rel = filename:join([PkgDir, "release", "erl.rel"]),

  ok = filelib:ensure_dir(Rel),

  ok = file:write_file(Rel, list_to_binary(io_lib:format("~p.\n", [R]))),

  %% Generate boot script for the release
  case systools:make_script(filename:rootname(Rel), [no_module_tests]) of
    ok ->
      ok;
    Error ->
      io:format("Error generating boot script for ~s:\n~p\n", [Rel, Error]),
      halt(1)
  end.


vsn_tuple(App) ->
  application:load(App),
  {ok, Vsn} = application:get_key(App, vsn),
  {App, Vsn}.


